CREATE DATABASE IF NOT EXISTS LOGIN_DB;
USE LOGIN_DB;


-- USERS TABLE
CREATE TABLE IF NOT EXISTS USERS(USER_ID INT NOT NULL, USER_NAME VARCHAR(50) NOT NULL, PASSWORD VARCHAR(128) NOT NULL);

-- CROP TABLE
CREATE TABLE IF NOT EXISTS CROPS(CROP_ID INT NOT NULL, CROP_NAME VARCHAR(50), CROP_IMAGE VARCHAR(255));

-- CROP_PESTS TABLE
CREATE TABLE IF NOT EXISTS CROP_PESTS(PEST_ID INT NOT NULL, PEST_NAME VARCHAR(50), PEST_DESCRIPTION VARCHAR(200));

-- SPRAY_INFO TABLE
CREATE TABLE IF NOT EXISTS SPRAY_INFO(SPRAY_ID INT NOT NULL, SPRAY_NAME VARCHAR(50), CROP_ID INT, PEST_ID INT, DISEASE_ID INT, SPRAYRATE_PER20L_WATER DOUBLE, SPRAY_INTERVAL DOUBLE, NUMBER_OF_SPRAYS INT);

-- CROP_DISEASES TABLE
CREATE TABLE IF NOT EXISTS CROP_DISEASES(DISEASE_ID INT NOT NULL, DISEASE_NAME VARCHAR(50), DISEASE_DESCRIPTION VARCHAR(200));

-- SEASEON TABLE
CREATE TABLE IF NOT EXISTS SEASON(SEASON_ID INT NOT NULL, CROP_ID INT, PLANT_SEASON VARCHAR(50));

-- SOIL PH TABLE
CREATE TABLE IF NOT EXISTS CROP_SOILPH(PH_ID INT NOT NULL, CROP_ID INT, PH_NUMBER VARCHAR(50));

-- FERTILIZER TABLE
CREATE TABLE IF NOT EXISTS FERTILIZER(FERTILIZER_ID INT NOT NULL,CROP_ID INT, FRTILIZER_NAME VARCHAR(50), FERTILIZER_DESCRIPTION VARCHAR(200));
--LOGIN TABLE
ALTER TABLE USERS RENAME TO LOGIN;

--CROPS TABLE
CREATE TABLE `crops` (
  `CROP_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CROP_NAME` varchar(50) DEFAULT NULL,
  `CROP_IMAGE` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`CROP_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4


--CROP_DISEASE TABLE